apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
  labels:
    app: authentication
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: server
          image: ghcr.io/team-evian-fiicode25/authentication:v0.7.0
          ports:
          - containerPort: 8080
          env:
          - name: MANDATORYFIELDS__USERNAME
            value: '1'
          - name: MANDATORYFIELDS__PHONENUMBER
            value: '0'
          - name: MANDATORYFIELDS__EMAIL
            value: '1'
          - name: DATABASE__MONGO__URL
            value: <redacted>
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  labels:
    app: authentication
spec:
  type: ClusterIP
  selector:
    app: authentication
  ports:
  - name: graphql
    port: 80
    targetPort: 8080
