apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-api
  labels:
    app: consumer-api
spec:
  selector:
    matchLabels:
      app: consumer-api
  template:
    metadata:
      labels:
        app: consumer-api
    spec:
      containers:
        - name: server
          image: ghcr.io/team-evian-fiicode25/consumer/api:v0.1.0-deployment-test18
          ports:
          - containerPort: 8000
          env:
          - name: AUTH_URL
            value: "http://authentication-service/graphql"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-api-service
  labels:
    app: consumer-api
spec:
  type: LoadBalancer
  selector:
    app: consumer-api
  ports:
  - name: http
    port: 80
    targetPort: 8000
