sslCertArn: "arn:aws:acm:eu-central-1:681273343657:certificate/d3bf9945-6fd3-4f8f-8270-83bbcf5a0a61"

authentication:
  name: authentication
  image: ghcr.io/team-evian-fiicode25/authentication
  tag: v0.7.0
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

consumer:
  name: consumer-api
  image: ghcr.io/team-evian-fiicode25/consumer/api
  tag: v0.1.0-deployment-test18
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
